name: run smoke tests..

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run: |
          docker run --rm --env FAUCET_TOKEN="${{ secrets.FAUCET_TOKEN }}" --env TG_API="${{ secrets.TG_API }}" significance/sig_smoke_tests_go:v42
