name: run smoke tests

on:
  push:

jobs:
  my_job:
    name: deploy to staging
    runs:
      using: 'docker'
      image: 'significance/sig_smoke_tests_go:v1'
    steps:
      - name: run tests
        run: "bash /go/src/app/run-bee.sh"
