name: run smoke tests

on:
  push:
  # schedule:
  #   - cron: '0 * * * *'

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    env: 
      FAUCET_TOKEN: ${{ secrets.FAUCET_TOKEN }}
    steps:
      - name: run tests
        run: |
          curl -vv -XPOST http://bee-gateway.duckdns.org:9999 --data token\=${{ secrets.FAUCET_TOKEN }}
          docker run --rm --env FAUCET_TOKEN="$FAUCET_TOKEN" significance/sig_smoke_tests_go:v32
