name: run smoke tests.....

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  smoke_test:
    env: 
      FAUCET_TOKEN: ${{ secrets.FAUCET_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run: |
          docker run --rm significance/sig_smoke_tests_go:v26
