name: run smoke tests.....

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  smoke_test:
    name: run smoke tests
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        env: 
          FAUCET_TOKEN: ${{ secrets.FAUCET_TOKEN }}
        run: |
          docker run --rm --env FAUCET_TOKEN="${{ secrets.FAUCET_TOKEN }}" significance/sig_smoke_tests_go:v25
