name: run script

on:
  push:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    container:
      image: significance/sig_smoke_tests_go:v1
      steps:
         - name: Log the parent container node version
           run: "bash /go/src/app/run-bee.sh"