name: run smoke tests.....

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  smoke_test:
    name: run smoke tests
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        env: 
          FAUCET_TOKEN: ${{ secrets.FAUCET_TOKEN }}
          TEST: ${{ secrets.TEST }}  
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.TEST }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.TEST}} | sed 's/./& /g' 
