name: run smoke tests..

on:
  push:

jobs:
  smoke_test:
    name: run smoke tests
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run: "docker run --rm significance/sig_smoke_tests_go:v13"
